Trim Internal Connections
AVanDeBrook/c-dependency-graph pull request #52
Opened 2020-10-28 21:30 UTC by corrinadelgreco

2020-10-28 22:48 UTC, samanthacombs approved these changes

2020-10-28 23:33 UTC, AVanDeBrook requested changes
Don't forget to comment out the `testargs` line in [`Manager.java`](https://github.com/AVanDeBrook/c-dependency-graph/blob/0091f3439a96cb41751d27c19a15f104ab479fe1/src/main/java/depgraph/Manager.java#L35). Otherwise it will ignore command-line arguments.

2020-10-29 00:08 UTC, spoofaloof requested changes
there's redundant code. there is no need to attempt to remove the internal nodes on the fly if we can do it at the end ( line 122-128 in parser dont need to be there). 

when doing the check in my clean-up edge function, we can simplify the code
...
the source and dest objects will never be null at this point so we can remove that bit
also, we can add a ! not to the .equals and keep the adding within the if and remove the else

2020-10-29 15:17 UTC, spoofaloof approved these changes

2020-10-29 16:06 UTC, merged